version: '3.5'

services:



  piatra_hartie_foarfeca:
    container_name: "piatra_hartie_foarfeca"
    build:
      context: ./docker/images/php
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./app:/app
      - ./config-php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config-php/php.ini:/etc/php/php.ini
      - ./config-php/pool.conf:/etc/php/pools/pool.conf
      - ./persistence/logs/php/:/var/log/php




  piatra_hartie_foarfeca-php-proxy:
    container_name: "piatra_hartie_foarfeca-php-proxy"
    image: nginx:latest
    expose:
      - 80
      - 443
    ports:
      - "8190:80"
    volumes:
      - ./app:/app
      - ./config:/etc/nginx/conf.d
      - ./persistence/logs/nginx:/var/log/nginx/
    environment:
      - NGINX_HOST=crm.autozumy.local
      - NGINX_PORT=80
    depends_on:
      - piatra_hartie_foarfeca
    links:
      - piatra_hartie_foarfeca
